-- SNS動画施策：参加同意と振込先口座情報
-- 口座情報はアプリケーション層で暗号化してから保存します。

CREATE TABLE IF NOT EXISTS public.sns_video_consents (
  line_uid text PRIMARY KEY,
  consented_at timestamptz NOT NULL DEFAULT now(),
  consent_message_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS sns_video_consents_message_id_unique
  ON public.sns_video_consents (consent_message_id)
  WHERE consent_message_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.sns_video_bank_account_drafts (
  line_uid text PRIMARY KEY,
  encrypted_draft text NOT NULL,
  current_step text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sns_video_bank_accounts (
  line_uid text PRIMARY KEY,
  bank_name_encrypted text NOT NULL,
  branch_name_encrypted text NOT NULL,
  account_type_encrypted text NOT NULL,
  account_number_encrypted text NOT NULL,
  account_holder_kana_encrypted text NOT NULL,
  submission_status text NOT NULL DEFAULT 'complete' CHECK (submission_status IN ('complete', 'needs_review')),
  submitted_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sns_video_bank_account_access_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  line_uid text NOT NULL,
  accessed_at timestamptz NOT NULL DEFAULT now(),
  access_purpose text NOT NULL DEFAULT 'payment_confirmation'
);

CREATE INDEX IF NOT EXISTS sns_video_bank_account_access_logs_line_uid_idx
  ON public.sns_video_bank_account_access_logs (line_uid, accessed_at DESC);

-- クライアント側の匿名キーでは参加同意・口座情報を読めないようにする。
-- Vercelのサーバー側Service Role KeyはRLSをバイパスし、認証済み管理APIだけが扱う。
ALTER TABLE public.sns_video_consents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sns_video_bank_account_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sns_video_bank_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sns_video_bank_account_access_logs ENABLE ROW LEVEL SECURITY;
